LOS Reference Server App/los.mobile/src/de/linogistix/mobile/common/gui/bean/BasicBackingBean.java
/*
 * BasicBackingBean.java
 *
 * Created on 2. Mai 2007, 05:23
 *
 * Copyright (c) 2006 LinogistiX GmbH. All rights reserved.
 *
 *<a href="http://www.linogistix.com/">browse for licence information</a>
 *
 */
package de.linogistix.mobile.common.gui.bean;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.ResourceBundle;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIViewRoot;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

import org.apache.log4j.Logger;
import org.mywms.ejb.BeanLocator;
import org.mywms.ejb.BeanLocatorException;
import org.mywms.model.Role;
import org.mywms.model.User;

import de.linogistix.los.query.exception.BusinessObjectNotFoundException;
import de.linogistix.los.user.query.UserQueryRemote;
import de.linogistix.los.util.BundleHelper;
import de.linogistix.mobile.processes.login.gui.bean.CenterBean;

/**
 * Basic utility operations for all BAcking Beans.
 * 
 * @author <a href="http://community.mywms.de/developer.jsp">Andreas
 *         Trautmann</a>
 */
public class BasicBackingBean {

	private static final Logger log = Logger.getLogger(BasicBackingBean.class.getName());

	//static JndiServiceResolver jndiServiceResolver;

	private UserQueryRemote userQuery;

	private Locale locale;

	/** Creates a new instance of BasicBackingBean */
	public BasicBackingBean() {

	}

	/**
	 * Resolves and adds a message to the FacesContext
	 * 
	 * @param clientId
	 *            if null, use global context. If empty use calling component
	 */
	public void message(String bundleKey, Object[] params, String clientId) {
		FacesMessage msg;
		String s;
		s = resolve(bundleKey, params);
		msg = new FacesMessage(s);
		if (clientId != null && clientId.length() == 0) {
			clientId = getUIViewRoot().getClientId(getContext());
		}
		getContext().addMessage(clientId, msg);
	}

	public void message(String message) {
		throw new ValidatorException(new FacesMessage(resolve(message, new Object[] {})));
	}

	

	/**
	 * Resolves a given ResourceBundle entry by key
	 */
	public String resolve(String key, Object[] parameters) {
		String ret;
		try {
			ResourceBundle bundle = getResourceBundle();
			ret = bundle.getString(key);
			if (parameters != null && parameters.length > 0) {
				ret = String.format(ret, parameters);
			}
			return ret;
		} catch (Throwable t) {
			return key;
		}
	}

	/**
	 * Resolves a given ResourceBundle entry by key
	 */
	public String resolve(String key) {
		Object[] parameters = new Object[] {};
		return resolve(key, parameters);
	}

	/**
	 * Resolves a given ResourceBundle entry by key and one parameter
	 */
	public String resolve(String key, String param) {
		Object[] parameters = new Object[] { param };
		return resolve(key, parameters);
	}

	/**
	 * @return current Locale of calling component
	 */
	public String getLocaleString() {

		if (this.locale == null) {
			return getLocale().toString();
		} else {
			return this.locale.toString();
		}

	}

	/**
	 * @return current Locale of calling component
	 */
	public Locale getLocale() {

		if (this.locale == null) {
			if (userQuery == null) {
				userQuery = getStateless(UserQueryRemote.class);
			}

			try {
				User user = userQuery.queryByIdentity(getPrincipalName());
				this.locale = BundleHelper.getLocale(user.getLocale());
			} catch (Throwable e) {
				log.error(e.getMessage(), e);
				this.locale = getUIViewRoot().getLocale();
			}
		}
		getUIViewRoot().setLocale(this.locale);
		return this.locale;

	}

	/**
	 * @return Calling component
	 */
	protected UIViewRoot getUIViewRoot() {
		UIViewRoot ret;
		ret = getContext().getViewRoot();
		return ret;
	}

	/**
	 * @return ResourceBundle for this Beans messages
	 */
	protected ResourceBundle getResourceBundle() {
		ResourceBundle bundle;
		Locale loc;
		loc = getUIViewRoot().getLocale();
		bundle = ResourceBundle.getBundle("de.linogistix.mobile.res.Bundle", loc);
		return bundle;
	}

	/**
	 * @return FacesContext.getCurrentInstance()
	 */
	public FacesContext getContext() {
		FacesContext context;

		context = FacesContext.getCurrentInstance();
		return context;
	}

	protected void reset(String beanName) {
		// dgrys new code portierung jboss, TODO dgrys test it
		// FacesContext.getCurrentInstance().getApplication().createValueBinding(
		// "#{beanName}").setValue(FacesContext.getCurrentInstance(), null);

		ExpressionFactory elFactory = getContext().getApplication().getExpressionFactory();
		ELContext elContext = getContext().getELContext();
		ValueExpression valueExp = elFactory.createValueExpression(elContext, "#{beanName}", Object.class);
		valueExp.setValue(elContext, null);
	}


	@SuppressWarnings("unchecked")
	protected <T> T getStateless(Class<T> remoteInterface) {
		String logStr = "getStateless ";
		log.debug(logStr + remoteInterface);

		
		T t = null;
		try {
			t = getBeanLocator().getStateless(remoteInterface);
		} catch (BeanLocatorException e) {
			log.error(logStr + e.getMessage());
		}

		return t;
	}
	
	private BeanLocator beanLocator = null;
	protected BeanLocator getBeanLocator() {
		String logStr = "getBeanLocator ";
		log.debug(logStr);
		
		if( beanLocator!=null ) {
			return beanLocator;
		}
		
		
		Properties props = new Properties();

		try {
			InputStream is;
			String file = "META-INF/appserver.properties";
			
		    is = BasicBackingBean.class.getClassLoader().getResourceAsStream(file);
			if (is != null) {
				props.load(is);
			} else{
				throw new RuntimeException(logStr+"Cannot read " + file );
			}

			is.close();
		} catch (FileNotFoundException e) {
			log.error(logStr+e.getLocalizedMessage());
		} catch (IOException e) {
			log.error(logStr+e.getLocalizedMessage());
		}

		try {
			beanLocator = new BeanLocator(props);
		} catch (BeanLocatorException e) {
			log.error(logStr + e.getMessage());
		}

		return beanLocator;

	}
	
	// TODO: Make LoginBean Available?
	protected CenterBean getLoginBean() {
		CenterBean b = (CenterBean) FacesContext.getCurrentInstance().getExternalContext().getSessionMap()
				.get("LoginBean");
		return b;
	}

	public String getPrincipalName() {
		ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
		return context.getUserPrincipal().getName();
	}

	public String[] getPrincipalRoles() {
		if (userQuery == null) {
			userQuery = getStateless(UserQueryRemote.class);
		}

		try {
			User user = userQuery.queryByIdentity(getPrincipalName());
			List<Role> roles = user.getRoles();
			String ret[] = new String[roles.size()];
			int i = 0;
			for (Role r : roles) {
				ret[i++] = r.getName();
			}
			return ret;

		} catch (BusinessObjectNotFoundException e) {
			log.error(e.getMessage(), e);
			return null;
		}

	}

	/**
	 * Overwrite in extended classes to check Security Constraints
	 * 
	 * @return
	 */
	public boolean isRolesAllowed() {
		String[] allowed;
		String[] roles;

		allowed = getRolesAllowed();
		if (allowed == null || allowed.length == 0) {
			return true;
		}

		roles = getPrincipalRoles();

		if ((allowed == null || allowed.length == 0) && (roles == null || roles.length == 0)) {
			return true;
		}

		for (String allow : allowed) {
			for (String role : roles) {
				if (allow.equals(role)) {
					return true;
				}
			}
		}

		return false;

	}

	public String[] getRolesAllowed() {
		return new String[0];
	}

	public String getWorkstationName() {
		// TODO krane: Give an identifier to the mobile devices. Maybe a
		// parameter in the URL or an extended login dialog
		return null;
	}
}

LOS Reference Server App/los.mobile/src/de/linogistix/mobile/processes/login/gui/bean/CenterBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.login.gui.bean;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ActionListener;
import javax.faces.validator.ValidatorException;
import javax.servlet.http.HttpServletRequest;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobile.processes.login.NavigationEnum;

/**
 * 
 * @author artur
 */
public class CenterBean extends BasicBackingBean implements ActionListener {
	String login;
	String password = "";
	String test;

	public String test() {
		System.out.println("test");
		return "";
	}

	public String getTest() {
		System.out.println("getTest");
		return "j_security_check";
	}

	public void setTest(String test) {
		System.out.println("setTest");
		this.test = test;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String loginActionPerformedListener() {
		/*
		 * ServletRequest request = (ServletRequest)
		 * FacesContext.getCurrentInstance().getExternalContext().getRequest();
		 * String s = (String)request.getAttribute("test");
		 * System.out.println("test = "+s);
		 */
		JSFHelper.getInstance().printRequest();
		JSFHelper.getInstance().printRequestMap();

		return NavigationEnum.controller_CenterPanel.toString();
	}

	public void validatePassword(FacesContext context, UIComponent component,
			Object value) throws ValidatorException {

	}

	public void beforePhase(javax.faces.event.PhaseEvent e) {
		HttpServletRequest req = (HttpServletRequest) e.getFacesContext()
				.getExternalContext().getRequest();
		req.getSession(true);

	}

	public void processAction(ActionEvent e) {

	}

}

LOS Reference Server App/los.mobile/src/de/linogistix/mobile/processes/controller/MenuBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.controller;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;
import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobileserver.processes.controller.ControllerFacade;
import de.linogistix.mobileserver.processes.controller.MobileFunction;


/**
 *
 * @author krane
 */
public class MenuBean extends BasicBackingBean {
	private static final Logger log = Logger.getLogger(MenuBean.class	.getName());

	
	private List<MenuAction> actions = null;
	private int numItems = 3;
	private int currentPage = 0;
	private ControllerFacade ctrlFacade;
	private boolean isInitialized = false;
	
    public MenuBean() {
    	super();
    	getLocale();
    	init();
    	isInitialized = true;
    }
    
    private void init() {
    	log.info("Init");
    	ctrlFacade = super.getStateless(ControllerFacade.class);

    	numItems = ctrlFacade.getMenuPageSize();
    	
    	actions = new ArrayList<MenuAction>();
    	
    	List<MobileFunction> fctList = ctrlFacade.getFunctions();
    	
    	for( MobileFunction fct : fctList ) {

			log.info("Add dialog " + fct.getClassName() );
			
    		BasicDialogBean dialog;
			try {
		        dialog = (BasicDialogBean) JSFHelper.getInstance().getSessionBeanForce( Class.forName(fct.getClassName()) );
			} catch (Throwable e) {
				log.error("Cannot instanciate dialog. Name="+fct.getClassName()+", Exception: " + e.getMessage(), e);
				continue;
			}
			if( dialog == null ) {
				log.error("Cannot instanciate dialog. Name="+fct.getClassName());
				continue;
			}
			
			dialog.init(fct.getArgs());
			
    		actions.add( new MenuAction( dialog.getTitle(), dialog.getNavigationKey() ) );
    	}
    	
    	
    	currentPage = 0;
    }

    
    /**
     * Just for the stupid picking dialog. It is not able to operate by itself.
     * Kill this method after building a stable picking dialog.
     */
    private void resetProcesses() {
    }
    public String getValue0() {
    	if( ! isInitialized ) {
    		init();
    	}
    	return getValue(0);
    }
    public String getValue1() {
    	return getValue(1);
    }
    public String getValue2() {
    	return getValue(2);
    }
    public String getValue3() {
    	return getValue(3);
    }
    public String getValue(int num) {
    	if(num >= numItems) {
    		return "";
    	}
    	int idx = (currentPage * numItems) + num;
    	return "" + ((actions.size() > idx) ? resolve(actions.get(idx).name) : "");
    }
    
    public String action0() {
    	return action(0);
    }
    public String action1() {
    	return action(1);
    }
    public String action2() {
    	return action(2);
    }
    public String action3() {
    	return action(3);
    }
    public String action(int num) {
    	resetProcesses();
    	int idx = (currentPage * numItems) + num;
    	return "" + ((actions.size() > idx) ? actions.get(idx).action : "");
    }
    
    public boolean getHasNextPage() {
    	int idx = (currentPage * numItems) + numItems;
    	return idx < actions.size();
    }
    
    public boolean getHasPrevPage() {
    	return currentPage > 0;
    }
    
    public String processNextPage() {
    	currentPage++;
    	return "";
    }

    public String processPrevPage() {
    	if( currentPage > 0 ) {
    		currentPage--;
    	}
    	return "";
    }
    
    public String processLogout(){
    	isInitialized = false;
        return "Logout";
    }

}


class MenuAction {
	String name;
	String action;
	
	MenuAction( String name, String action ) {
		this.name = name;
		this.action = action;
	}
}

LOS Reference Server App/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ControllerFacadeBean.java
/*
 * Copyright (c) 2010 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

@Stateless
public class ControllerFacadeBean implements ControllerFacade {

	@EJB
	private ManageMobile mobileService;
	
	
	public List<MobileFunction> getFunctions() {
		return mobileService.getFunctions();
	}
	
	
	public int getMenuPageSize() {
		return mobileService.getMenuPageSize();
	}
	
}

LOS Reference Server App/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ManageMobileBean.java
/*
 * Copyright (c) 2010-2013 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import javax.ejb.Stateless;

import de.linogistix.los.inventory.model.LOSPickingOrder;
import de.linogistix.mobileserver.processes.picking.PickingMobileComparator;
import de.linogistix.mobileserver.processes.picking.PickingMobilePos;


public class ManageMobileBean implements ManageMobile {
	
	
	public List<MobileFunction> getFunctions() {
		List<MobileFunction> functionList = new ArrayList<MobileFunction>();
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.info.InfoBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.goodsreceipt.GoodsReceiptBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.storage.StorageBackingBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.gr_direct.GRDirectBean", "MODE_GOODS_RECEIPT") );
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.gr_direct.GRDirectBean", "MODE_MATERIAL") );
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.picking.PickingMobileBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.shipping.ShippingBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.replenish.ReplenishMobileBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.stocktaking.StockTakingBean"));
		
		return functionList;
	}
	

	public int getMenuPageSize() {
		return 3;
	}
	
	public Comparator<PickingMobilePos> getPickingComparator() {
		return new PickingMobileComparator(false);
	}
	
	public String getPickingSelectionText(LOSPickingOrder pickingOrder) {
		return pickingOrder.getNumber();
	}
}

LOS Reference Server App/los.mobile/WebContent/pages/processes/controller/MainMenu.jsp
<%-- 
  Copyright (c) 2006 - 2013 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>
<%-- <%@ taglib uri="http://richfaces.org/a4j" prefix="a4j"%>
<%@ taglib uri="http://richfaces.org/rich" prefix="rich"%> --%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="expires" content="Mon, 01 Jan 1990 00:00:01 GMT">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
         <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" />
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">                    
        <f:view locale="#{MenuBean.locale}">
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" /> 
            
            
                        
            <h:form id="Form" styleClass="form">

                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
                	<h:outputText id="pagetitle" 
                		value="#{bundle.Startside} (#{MenuBean.principalName})" 
                		styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>

                <div class="space">
                    <h:messages id="messages" styleClass="error"/> 
                    <table width="100%" border="0" style="padding-top:5px">
                        
                        <tr>
                            <td>
                                <h:commandButton id="BUTTON_0" 
                                	value="#{MenuBean.value0}"
                                	action="#{MenuBean.action0}" 
                                	rendered="#{MenuBean.value0 != ''}" 
                                	style="width:100%" styleClass="commandButton"/>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h:commandButton id="BUTTON_1" 
                                	value="#{MenuBean.value1}" 
                                	action="#{MenuBean.action1}" 
                                	rendered="#{MenuBean.value1 != ''}" 
                                	style="width:100%" styleClass="commandButton"/>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h:commandButton id="BUTTON_2" 
                                	value="#{MenuBean.value2}" 
                                	action="#{MenuBean.action2}" 
                                	rendered="#{MenuBean.value2 != ''}" 
                                	style="width:100%" styleClass="commandButton"/>
                            </td>
                        </tr>   
                        <tr>
                            <td>
                                <h:commandButton id="BUTTON_3" 
                                	value="#{MenuBean.value3}" 
                                	action="#{MenuBean.action3}"
                                	rendered="#{MenuBean.value3 != ''}" 
                                	style="width:100%" styleClass="commandButton"/>
                            </td>
                        </tr>
            
                    </table>     
                </div>
                
                <%-- Command Buttons --%>
                <div class="buttonbar">  
                    <h:commandButton id="BUTTON_LOGOUT" 
	                				 value="#{bundle.Logout}" 
	                				 action="#{MenuBean.processLogout}" 
	                				 styleClass="commandButton"  />
					&#160;
					<h:commandButton id="BUTTON_PREV" 
                				 value="<" 
                				 action="#{MenuBean.processPrevPage}" 
                				 styleClass="navigateButton"
                				 rendered="#{MenuBean.hasPrevPage || MenuBean.hasNextPage}"
                				 disabled="#{!MenuBean.hasPrevPage}" />
                    <h:commandButton id="BUTTON_NEXT" 
                				 value=">" 
                				 action="#{MenuBean.processNextPage}" 
                				 styleClass="navigateButton" 
                				 rendered="#{MenuBean.hasPrevPage || MenuBean.hasNextPage}"
                				 disabled="#{!MenuBean.hasNextPage}" /> 
	            </div>
                                
            </h:form>            
        </f:view>     
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    

            function setFocus() {
                document.getElementById('Form:BUTTON_0').focus();
            }    
            
        </script>
    </body>
</html>